version: "3"
services:
  sonarr:
    image: linuxserver/sonarr
    ports:
      - "${SONARR_PORT}:8989"
    volumes:
      - "${SONARR_PATH_TO_CONFIG}:/config"
      - "${SONARR_PATH_TO_TV_SERIES}:/tv"
      - "${SONARR_PATH_TO_DOWNLOADS}:/downloads"
    links:
      - deluge
    environment:
      - TZ
      - PGID
      - PUID

  medusa:
    image: linuxserver/medusa
    ports:
      - "${MEDUSA_PORT}:8081"
    volumes:
      - "${MEDUSA_PATH_TO_CONFIG}:/config"
      - "${MEDUSA_PATH_TO_TV_SERIES}:/tv"
      - "${MEDUSA_PATH_TO_DOWNLOADS}:/downloads"
    links:
      - deluge
    environment:
      - TZ
      - PGID
      - PUID

  deluge:
    image: binhex/arch-delugevpn
    ports:
      - "8112:8112"
      - "8118:8118"
      - "58846:58846"
      - "58946:58946"
    cap_add:
      - NET_ADMIN
    volumes:
      - "${DELUGE_PATH_TO_CONFIG}:/config"
      - "${MEDUSA_PATH_TO_TV_SERIES}:/tv"
      - "${MEDUSA_PATH_TO_DOWNLOADS}:/downloads"
      - "${MEDUSA_PATH_TO_DOWNLOADS}:/data"
    environment:
      - VPN_ENABLED
      - VPN_USER
      - VPN_PASS
      - VPN_PROV
      - PUID
      - PGID
      - TZ
      - NAME_SERVERS
      - DEBUG
      - LAN_NETWORK
      - ENABLE_PRIVOXY=no
      - STRICT_PORT_FORWARD=yes
      - UMASK=002

  emby:
    image: emby/embyserver:latest
    volumes:
      - "${EMBY_PATH_TO_CONFIG}:/config"
      - "${MEDUSA_PATH_TO_TV_SERIES}:/mnt/share1"
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    ports:
      - "8096:8096"
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - GIDLIST=44

  

  deluge_proxy: 
    image: nginx
    ports:
      - "8080:80"
    links:
      - deluge
    volumes:     
      - ./deluge.webuiproxy.nginx.conf:/etc/nginx/conf.d/default.conf

  organizr:
    image: lsiocommunity/organizr
    volumes:
      - "${ORGANIZR_PATH_TO_CONFIG}:/config"
    ports:
      - "80:80"
    environment:
      - PGID
      - PUID

